version: '3'

services:
   client:
     volumes:
       - ./client:/app:ro 
   server:
     volumes:
       - ./server:/app:ro    
   mongo-express:
    image: mongo-express
    restart: always
    depends_on:
     - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

 

