version: '3'

name : "chat-app-real-ime"

services:
 client:
    build: ./client  
    container_name: chat_app_client
    depends_on:
      - server
    env_file:
      - ./client/.env
    ports: 
      - "3000:3000"
    volumes:
      - ./client:/app:ro 

 server:
   build: ./server  
   container_name: chat_app_server
   depends_on:
     - mongo
     - cache
   env_file:
      - ./server/.env
   ports: 
     - "8000:8000"
   

 mongo:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
     - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

 cache:
    image: redis
    container_name: redisdb_cashing
    restart: always
    ports:
      - '6379:6379'

volumes:
  mongodb:  
    name: "mongodb" 